.github/workflows/buildcdn.yml

In order to get the date to update with each release

Use different release mechanism

---

sdcard/horus/WIDGETS/LibGUI/libgui.lua
sdcard/horus/WIDGETS/LibGUI/loadable.lua
sdcard/horus/WIDGETS/LibGUI/main.lua

Also added date stamps to headers

Use edit color

---

sdcard/horus/WIDGETS/EventDemo/loadable.lua
sdcard/horus/WIDGETS/LibGUI/libgui.lua
sdcard/horus/WIDGETS/LibGUI/loadable.lua

Added sliders
Added dropDown field
Changed the names of colors
GUI.menu(...) returns a table with all of the individual menu elements

Several changes

---

README.md

Link goes to latest instead of a fixed version

Updated the link to the voice generator repo

---

other/default_background_480x320.svg

Background for 480x320 pixel color radios such as PL18/PL18EV

480x320 bg from mhotar

---

sdcard/horus/TEMPLATES/PERSONAL/about.txt
sdcard/horus/TEMPLATES/SoarETX/F3K TRAD.txt
sdcard/horus/TEMPLATES/SoarETX/F3K TRAD.yml
sdcard/horus/TEMPLATES/SoarETX/F3K.txt
sdcard/horus/TEMPLATES/SoarETX/F3K.yml
sdcard/horus/TEMPLATES/SoarETX/about.txt
sdcard/horus/WIDGETS/LibGUI/libgui.lua
sdcard/horus/WIDGETS/LibGUI/loadable.lua
sdcard/horus/WIDGETS/LibGUI/main.lua
sdcard/horus/WIDGETS/SoarETX/1/battery.lua
sdcard/horus/WIDGETS/SoarETX/1/f3k.lua
sdcard/horus/WIDGETS/SoarETX/1/f3k_ctr.lua
sdcard/horus/WIDGETS/SoarETX/1/f3k_mix.lua
sdcard/horus/WIDGETS/SoarETX/1/f3k_sw.lua
sdcard/horus/WIDGETS/SoarETX/1/name.lua
sdcard/horus/WIDGETS/SoarETX/1/outputs.lua
sdcard/horus/WIDGETS/SoarETX/1/wing2.lua
sdcard/horus/WIDGETS/SoarETX/main.lua

... I think!
- Simplified sliders 
- Added drawTriangle to translated versions for sub GUIs
- Added function to move the focused element
- Modified scrolling state so the focused element only receives SLIDE events if it were touched at the beginning of the scroll

Ready for 1.0.0

---

README.md
sdcard/taranis-x7/SCRIPTS/TOOLS/WizardLoader.lua

- Added Wizard Loader script on B/W 128x64 Screen.
- Added ZORRO in Readme.

Wizard Loader script on B/W 128x64 Screen

---

sdcard/horus/WIDGETS/SoarETX/1/graph.lua

@pfeerick please pull in as soon as it is convenient for you!

Added a number of checks to graph widget

---

sdcard/horus/WIDGETS/TxGPStest/main.lua

Removed spurious commands

---

sdcard/horus/WIDGETS/LibGUI/libgui.lua

Small improvement so the touched element gets selected when the menu is activated by a touch

Improved touch on non-active menu

---

sdcard/c480x272/WIDGETS/SoarETX/1/f3k.lua

Fixed bug in Big Ladder task

---

sdcard/c480x272/SCRIPTS/TOOLS/DSM_AR636_Tel.lua
sdcard/c480x272/SCRIPTS/TOOLS/DSM_SmartRX_Tel.lua

Scripts to show DSM Telemetry Data
1. Flight mode / Gyro Settings info
2. Smart Batterty/ESC status
3. Various Blade Heli Helpers
4. TextGen (Ex: Avian ESC programming from the TX)

#98  Lua Scripts for DSM Telemetry + TextGen

---

sdcard/c480x272/TEMPLATES/1.Wizard/3.Wing.lua
sdcard/c480x272/TEMPLATES/1.Wizard/3.Wing.yml

- fix is_arm switch
- internal updates
- use long <ENTER> to acknowledge

wing wizard update

---

README.md
sdcard.json

readme: add RadioMaster MT12

---

sdcard/c480x272/TEMPLATES/1.Wizard/1.Plane.lua

fixes https://github.com/EdgeTX/edgetx-sdcard/issues/156

fix: use configured DR switch in plane wizard

---

sdcard/c320x480/SCRIPTS/WIZARD/glider/wizard.lua
sdcard/c320x480/SCRIPTS/WIZARD/plane/wizard.lua
sdcard/c320x480/WIDGETS/Flights/main.lua
sdcard/c480x272/SCRIPTS/PRESETS/engine/lib_utils.lua
sdcard/c480x272/SCRIPTS/PRESETS/engine/main.lua
sdcard/c480x272/SCRIPTS/TOOLS/FlightsHistory/FlightsHistory3.lua
sdcard/c480x272/SCRIPTS/TOOLS/FlightsHistory/main.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_S8R_S6R/S8R_calibrate.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_S8R_S6R/S8R_setup.lua
sdcard/c480x272/SCRIPTS/TOOLS/Model Locator (by RSSI).lua
sdcard/c480x272/TEMPLATES/1.Wizard/1.Plane.lua
sdcard/c480x272/TEMPLATES/1.Wizard/2.Glider.lua
sdcard/c480x272/TEMPLATES/1.Wizard/3.Wing.lua
sdcard/c480x272/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c480x272/TEMPLATES/1.Wizard/5.Multirotor.lua
sdcard/c480x272/WIDGETS/Flights/main.lua
sdcard/c480x272/WIDGETS/Ghost/main.lua
sdcard/c480x320/SCRIPTS/TOOLS/Model Locator (by RSSI).lua
sdcard/c480x320/SCRIPTS/TOOLS/WizardLoader.lua
sdcard/c480x320/SCRIPTS/WIZARD/glider.lua
sdcard/c480x320/SCRIPTS/WIZARD/multirotor.lua
sdcard/c480x320/SCRIPTS/WIZARD/plane.lua
sdcard/c480x320/WIDGETS/Ghost/main.lua

chore: replace deprecated 'Bitmap'.

---

sdcard/c480x272/SCRIPTS/TOOLS/Model Locator (by RSSI).lua
sdcard/c480x320/SCRIPTS/TOOLS/Model Locator (by RSSI).lua

model locator: display error info when no signal found

---

sdcard/c480x272/WIDGETS/SoarETX/2/ailctr.lua
sdcard/c480x272/WIDGETS/SoarETX/2/brkcrv.lua
sdcard/c480x272/WIDGETS/SoarETX/2/f3J.lua
sdcard/c480x272/WIDGETS/SoarETX/2/f3k.lua
sdcard/c480x272/WIDGETS/SoarETX/2/f5J.lua
sdcard/c480x272/WIDGETS/SoarETX/2/graph.lua
sdcard/c480x272/WIDGETS/SoarETX/2/mixes.lua
sdcard/c480x272/WIDGETS/SoarETX/2/outputs.lua
sdcard/c480x272/WIDGETS/SoarETX/2/switch.lua
sdcard/c480x272/WIDGETS/SoarETX/2/wing2.lua
sdcard/c480x272/WIDGETS/SoarETX/2/wing4.lua
sdcard/c480x320/WIDGETS/SoarETX/2/ailctr.lua
sdcard/c480x320/WIDGETS/SoarETX/2/brkcrv.lua
sdcard/c480x320/WIDGETS/SoarETX/2/f3J.lua
sdcard/c480x320/WIDGETS/SoarETX/2/f3k.lua
sdcard/c480x320/WIDGETS/SoarETX/2/f5J.lua
sdcard/c480x320/WIDGETS/SoarETX/2/graph.lua
sdcard/c480x320/WIDGETS/SoarETX/2/mixes.lua
sdcard/c480x320/WIDGETS/SoarETX/2/outputs.lua
sdcard/c480x320/WIDGETS/SoarETX/2/switch.lua
sdcard/c480x320/WIDGETS/SoarETX/2/wing2.lua
sdcard/c480x320/WIDGETS/SoarETX/2/wing4.lua

Globally use the regular font and only change it on the specific GUI object.

fix(SoarETXv2): wrong font sizes on several screens

---

sdcard/c480x272/WIDGETS/MicroValues/app.lua
sdcard/c480x272/WIDGETS/MicroValues/lib_log.lua
sdcard/c480x272/WIDGETS/MicroValues/lib_widget_tools.lua
sdcard/c480x272/WIDGETS/MicroValues/main.lua

new widget to allow more values on top bar
each instance include 2 values instead of a single one
so in 4 (out of the 6) area we can now put 8 values
---

feat(color): multi-values widget

---

sdcard/c480x272/WIDGETS/Value2/lib_widget_tools.lua
sdcard/c480x272/WIDGETS/Value2/main.lua

support min/max values selection
add options translations for better usability

value2: min/max values selection, support option translations

---

sdcard/bw212x64/UTILITIES/MultiConfigExternal.lua
sdcard/bw212x64/UTILITIES/MultiConfigInternal.lua
sdcard/c320x480/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c320x480/TEMPLATES/1.Wizard/5.Multirotor.lua
sdcard/c480x272/SCRIPTS/TOOLS/FlightsHistory/main.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/FrSky_S8R_S6R/calibrate.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/FrSky_S8R_S6R/setup.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/SRx_plus/calibrateV1.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/SRx_plus/calibrateV3.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/SRx_plus/setupV1.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/SRx_plus/setupV3.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/SRx_plus/stickCalibrateV3.lua
sdcard/c480x272/SCRIPTS/TOOLS/FrSky_Gyro_Suite/main.lua
sdcard/c480x272/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c480x272/TEMPLATES/1.Wizard/5.Multirotor.lua
sdcard/c480x272/WIDGETS/TxGPStest/main.lua
sdcard/c480x320/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c480x320/TEMPLATES/1.Wizard/5.Multirotor.lua
sdcard/c480x320/WIDGETS/TxGPStest/main.lua

chore: replace deprecated color constants

---

sdcard/c480x272/WIDGETS/GaugeRotary/gauge_core.lua
sdcard/c480x272/WIDGETS/GaugeRotary/lib_log.lua
sdcard/c480x272/WIDGETS/GaugeRotary/lib_sensors.lua
sdcard/c480x272/WIDGETS/GaugeRotary/lib_widget_tools.lua
sdcard/c480x272/WIDGETS/GaugeRotary/main.lua
sdcard/c480x320/WIDGETS/GaugeRotary/gauge_core.lua
sdcard/c480x320/WIDGETS/GaugeRotary/lib_log.lua
sdcard/c480x320/WIDGETS/GaugeRotary/lib_sensors.lua
sdcard/c480x320/WIDGETS/GaugeRotary/lib_widget_tools.lua
sdcard/c480x320/WIDGETS/GaugeRotary/main.lua

GaugeRotary: enhanced telemetry

---

sdcard/bw128x64/SCRIPTS/WIZARD/heli.lua
sdcard/bw212x64/SCRIPTS/WIZARD/heli.lua
sdcard/c320x240/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c320x480/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c480x272/TEMPLATES/1.Wizard/4.Helicopter.lua
sdcard/c480x320/TEMPLATES/1.Wizard/4.Helicopter.lua

The source for the gyro (T.gain) was updated on each SD file type to the correct source (MAX)

fix(wizard): incorrect index for MAX source in heli wizard
