- .github/workflows/buildcdn.yml
This PR is an attempt at preventing the upload job from running if the action is being run on a pull request, as the jobs will always fail. And I can't believe that actually worked first time! :partying_face:
> Prevent `uploadrelease` job running on PRs

- sdcard/horus/WIDGETS/TxGPStest/main.lua
In addition to new top-bar icon ( [https://github.com/EdgeTX/edgetx/pull/50](https://github.com/EdgeTX/edgetx/pull/50) ) this widget displays further GPS data of the radio and is targeted for testing the GPS function.
Based on an example by 3djc: https://github.com/opentx/opentx/pull/5610
> Radio GPS test widget

- generate.sh
Prevent a subdirectory being created, so that the zip file accurately represents the state of the SD card, and hopefully allowing the flasher to work better.
> Put the SD card content in root of zip, not subdir

- sdcard/horus/WIDGETS/EventDemo/loadable.lua
- sdcard/horus/WIDGETS/LibGUI/libgui.lua
- sdcard/horus/WIDGETS/LibGUI/loadable.lua
- sdcard/horus/WIDGETS/LibGUI/main.lua
LibGUI shows a way to create a GUI with buttons, menus etc.
> Added LibGUI, and updates to EventDemo

- sdcard/horus/WIDGETS/BattCheckAn/main.lua
- sdcard/horus/WIDGETS/Batt_A1/main.lua
horus widget: Widget to display the levels of lipo battery from single analog source (like the VFAS/A1/A2/mini-quad-flight-controller)
> horus widget: Widget to display the levels of Lipo battery from single analog source

- sdcard/horus/WIDGETS/EventDemo/loadable.lua
- sdcard/horus/WIDGETS/LibGUI/libgui.lua
- sdcard/horus/WIDGETS/LibGUI/loadable.lua
After I labeled my last PR RC1, I got some new ideas and decided to go for it. So this is a completely _new_ RC1...
GUIs can now be nested as editable elements, so one can have subgroups of elements, and a new _custom_ element gives some hooks into the system to make new types of GUI elements.
> Nested GUIs

- sdcard/horus/WIDGETS/Timer2/main.lua
- sdcard/nv14/WIDGETS/Timer2/main.lua
fix issue #49 
- fix negative timer display
- color red on negative display
before the fix:
after the fix:
> fix negative timer display

- sdcard/horus/WIDGETS/GaugeRotary/gauge_core.lua
- sdcard/horus/WIDGETS/GaugeRotary/main.lua
This Rotary Gauge widget display a fancy old style analog gauge with needle
Options:
HighAsGreen: [checked] for sensor that high values is good (RSSI/Fuel/...)
- [checked] for sensor that high values is good (RSSI/Fuel/...)
- [un-checked] for sensor that low values is good (Temp/Battery/...)
Note: if the min & max input value are -1, widget will automatically select min/max based on the source name.
common sources are:
-    RSSI
-    Temp
-    rpm
-    fuel
-    vibration (heli)
-    Transmitter Battery
-    batt-capacity
-    A1/A2 analog voltage
> new Rotary Gauge widget

- sdcard/c480x272/WIDGETS/LibGUI/libgui.lua
- sdcard/c480x272/WIDGETS/SoarETX/1/battery.lua
- sdcard/c480x272/WIDGETS/SoarETX/1/f3k.lua
- sdcard/c480x272/WIDGETS/SoarETX/main.lua
Work arounds for known Lua bugs in 2.8:
1) Top bar widgets never run `background()` - also not when another widget is in fullscreen. Therefore, the battery monitor does not run when another widget is in fullscreen.
2) `EVT_VIRTUAL_ENTER_LONG` is pushed when finger dragging on screen (should only give `EVT_TOUCH_SLIDE`).
Adjustment for wider space character for large font sizes.
> SoarETX for 2.8

- sdcard/c480x272/WIDGETS/SerialPower/loadable.lua
- sdcard/c480x272/WIDGETS/SerialPower/main.lua
* Adds SerialPower widget to control the serial port power from LUA. Makes use of new LUA API additions `serialGetPower()` and `serialSetPower()` from https://github.com/EdgeTX/edgetx/pull/3265
Tested on RM TX16S.
Screenshot from physical radio:
When ran in simulator or non serial power capable 480x272 pixel color screen radio, the output will be:
> feat: Adds SerialPower widget to control the serial port power from LUA

- sdcard/bw128x64/SCRIPTS/RGBLED/blue.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/green.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/off.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/police.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/red.lua
Support for https://github.com/EdgeTX/edgetx/pull/3909
> Add basic RGB leds script support

- sdcard/bw128x64/SCRIPTS/RGBLED/Bback.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/Bfwrd.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/Pback.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/Pfwrd.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/blue.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/cycle.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/flow.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/green.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/orange.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/purple.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/rainbw.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/rgbLop.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/runner.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/sapp.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/white.lua
- sdcard/bw128x64/SCRIPTS/RGBLED/yellow.lua
I used Github Copilot and, referencing some existing Scripts, wrote some new cool LED light scripts for the MT12, hoping these scripts will be adopted.
> Add more RGB LED lua scripts for MT12

- sdcard/c480x272/WIDGETS/SoarETX/1/f3k_sw.lua
- sdcard/c480x272/WIDGETS/SoarETX/1/f3kre_sw.lua
- sdcard/c480x272/WIDGETS/SoarETX/2/switch.lua
- sdcard/c480x320/WIDGETS/SoarETX/1/f3k_sw.lua
- sdcard/c480x320/WIDGETS/SoarETX/1/f3kre_sw.lua
- sdcard/c480x320/WIDGETS/SoarETX/2/switch.lua
Fixes #142
The way to find the switches worked in 2.9.4, but not in 2.10.  Fixing it to a way that works for both.
The correction is for both version 1 (backward compatibility), and new v2.
The code  for firmware 2.9.x (and before) was looking for a "trim" with name "Rl" to identify the "last" switch.. looks like is no longer there in 2.10.
Change the code to identify the switches using a pattern.
> fix(SoarETX):  Replace the way to identify the radio Switches

- sdcard/c480x272/WIDGETS/LibGUI/libgui.lua
- sdcard/c480x320/WIDGETS/LibGUI/libgui.lua
Fixes #153 
Fix LibGUI to be backward compatible when calling the method "update()" who was renamed to "onUpdate()".
Now works both ways.
It was braking SoarETX, but we really don't know if other scripts using LibGui could have the same problem.
> LibGUI: onUpdate() backward compatibility

- sdcard/c480x272/WIDGETS/SoarETX/2/switch.lua
- sdcard/c480x320/WIDGETS/SoarETX/2/switch.lua
Fix formatting issue for the page "Switches" for F5J model.
Before:
After:
> fix(SoarETXv2): wrong sized widget text for F5J

- sdcard/c480x272/WIDGETS/LibGUI/libgui.lua
- sdcard/c480x272/WIDGETS/LibGUI/loadable.lua
- sdcard/c480x320/WIDGETS/LibGUI/libgui.lua
- sdcard/c480x320/WIDGETS/LibGUI/loadable.lua
needs PR https://github.com/EdgeTX/edgetx/pull/5587
> Add momentary button

- sdcard/c480x272/SCRIPTS/TOOLS/Model Locator (by RSSI).lua
- sdcard/c480x320/SCRIPTS/TOOLS/Model Locator (by RSSI).lua
This change adds the current TX power so that people can see if they are on 25mW or not when using the locator. Additionally adds haptic feedback for those hard of hearing or those who just like it
> RSSI Model Locator: Add TX Power & Haptic Feedback

- sdcard/c480x272/TEMPLATES/1.Wizard/3.Wing.lua
fix dual rate switch display on config summary
and correct actual setting 
Fixes #172
> wing wizard: fix dual rate switch display & setting

- sdcard/c480x320/WIDGETS/BattAnalog/lib_log.lua
- sdcard/c480x320/WIDGETS/BattAnalog/lib_sensors.lua
- sdcard/c480x320/WIDGETS/BattAnalog/lib_widget_tools.lua
- sdcard/c480x320/WIDGETS/BattAnalog/logic.lua
- sdcard/c480x320/WIDGETS/BattAnalog/main.lua
- sdcard/c480x320/WIDGETS/BattAnalog/ui_lvgl.lua
- sdcard/c480x320/WIDGETS/GaugeRotary/gauge_core.lua
- sdcard/c480x320/WIDGETS/GaugeRotary/lib_log.lua
- sdcard/c480x320/WIDGETS/GaugeRotary/lib_widget_tools.lua
- sdcard/c480x320/WIDGETS/GaugeRotary/main.lua
- sdcard/c480x320/WIDGETS/Timer2/main.lua
update widgets that can run on 480x320 from main folder
* BattAnalog
* Timer2
* GaugeRotary
*
> feat: update 480x320 BattAnalog, Timer2, GaugeRotary widgets

- sdcard/c480x272/TEMPLATES/1.Wizard/3.Wing.lua
> fix(wizard): respect radio default channel order when deleting rudder input

- sdcard/c480x272/WIDGETS/BattAnalog/logic.lua
- sdcard/c480x272/WIDGETS/BattAnalog/main.lua
- sdcard/c480x272/WIDGETS/BattAnalog/ui_lvgl.lua
- widget can now generate "cell" telemetry sensor, so logical-switch & sound can be apply with 3.6-4.2 values instead of full voltage 
- fix: when selecting cells, the min value is not working
- fix: when selecting 8/10/12 cells, there is misalignment
- add support for 7 cells
> fix(BattAnalog): misalignment when selecting 8/10/12 cells, min value not working, add "cell" sensor
